apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: certs.certcontroller.5ik8s.com
spec:
  group: certcontroller.5ik8s.com
  version: v1beta1
  names:
    kind: Cert
    plural: certs
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            secretName:
              type: string
            domain:
              type: string
            type:
              type: string
            validityPeriod:
              type: integer
              minimum: 1
              maximum: 89
            env:
              type: object
          required:
            - secretName
            - domain
            - type
            - validityPeriod

